### ISSUE TITLE
[Enhancement] DB 수정 및 리팩토링

### ISSUE THREAD

**Issue by abcworld123** [AUTOINVEN/autoinven#93]
## TODO
- [ ] 창고 대여 시 usableArea가 줄어들지 않도록 수정
- [ ] 창고 연락처 (메일, 전화) 칼럼 추가
- [ ] Contract 테이블의 contractID를 reqID로 변경
- [ ] RequestForBuy 테이블의 reqType이 ReqPayByBuyer인 상태에서 Buyer가 결제 시 행을 삭제하고, Contract 테이블에 등록되도록 수정
